# Generated by Django 5.2 on 2025-04-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfitrecommendation',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfitrecommendation',
            name='percentage_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
